# Generated by Django 4.2.4 on 2023-09-05 03:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARMAZENAMENTO_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARMAZENAMENTO_1', models.CharField(choices=[('ARMAZENAMENTO_1', 'UNIDADES DE ARMAZENAMENTO 1')], max_length=100, verbose_name='ARMAZENAMENTO_1')),
                ('STATUS_DA_UNIDADE_DE_ARMAZENAMENTO_1', models.CharField(choices=[('Ativado', '🟩'), ('Desativado', '🟥')], default='Ativado', max_length=50, verbose_name='STATUS_DA_UNIDADE_DE_ARMAZENAMENTO_1')),
                ('STATUS_DE_SAIDA_DE_ARMAZENAMENTO_1', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=50, verbose_name='STATUS_DE_SAIDA_DE_ARMAZENAMENTO_1')),
                ('STATUS_DE_APARELHO_DE_ARMAZENAMENTO_1', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=50, verbose_name='STATUS_DE_APARELHO_DE_ARMAZENAMENTO_1')),
                ('STATUS_DE_ENTRADA_DE_ARMAZENAMENTO_1', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=50, verbose_name='STATUS_DE_ENTRADA_DE_ARMAZENAMENTO_1')),
                ('Nivel_de_Potencia_das_Bombas', models.IntegerField(blank=True, default=None, editable=models.Q(('ARMAZENAMENTO_1', 'ARMAZENAMENTO_1')), null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel de Potencia das Bombas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ARMAZENAMENTO_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARMAZENAMENTO_2', models.CharField(choices=[('ARMAZENAMENTO_2', 'UNIDADES DE ARMAZENAMENTO 2')], max_length=50, verbose_name='ARMAZENAMENTO_2')),
                ('STATUS_DA_UNIDADE_DE_ARMAZENAMENTO_2', models.CharField(choices=[('Ativado', '🟩'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DA_UNIDADE_DE_ARMAZENAMENTO_2')),
                ('STATUS_DE_SAIDA_DE_ARMAZENAMENTO_2', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DE_SAIDA_DE_ARMAZENAMENTO_2')),
                ('STATUS_DE_APARELHO_DE_ARMAZENAMENTO_2', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DE_APARELHO_DE_ARMAZENAMENTO_2')),
                ('STATUS_DE_ENTRADA_DE_ARMAZENAMENTO_2', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DE_ENTRADA_DE_ARMAZENAMENTO_2')),
                ('Nivel_do_Tanque', models.IntegerField(blank=True, default=None, editable=models.Q(('ARMAZENAMENTO_2', 'ARMAZENAMENTO 2')), null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel do Tanque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GRADEAMENTO_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRADEAMENTO_1', models.CharField(choices=[('UNIDADES DE GRADEAMENTO 1', 'UNIDADES DE GRADEAMENTO 1')], max_length=50, verbose_name='GRADEAMENTO_1')),
                ('STATUS_DA_UNIDADE_DE_GRADEAMENTO_1', models.CharField(choices=[('Ativado', '🟩'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DA_UNIDADE_DE_GRADEAMENTO_1')),
                ('STATUS_DE_SAIDA_DE_GRADEAMENTO_1', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DE_SAIDA')),
                ('STATUS_DE_APARELHO_DE_GRADEAMENTO_1', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DE_APARELHO_DE_GRADEAMENTO_1')),
                ('STATUS_DE_ENTRADA_DE_GRADEAMENTO_1', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DE_ENTRADA_DE_GRADEAMENTO_1')),
                ('STATUS_DO_RASPADOR_DE_GRADEAMENTO_DE_GRADEAMENTO_1', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DO_RASPADOR_DE_GRADEAMENTO_1')),
                ('Nivel_do_Compartimento_de_gradeamento', models.IntegerField(blank=True, default=None, editable=models.Q(('GRADEAMENTO_1', 'UNIDADE DE GRADEAMENTO 1')), null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nivel do Compartimento de Gradeamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GRADEAMENTO_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRADEAMENTO_2', models.CharField(choices=[('UNIDADES DE GRADEAMENTO 2', 'UNIDADES DE GRADEAMENTO 2')], max_length=50, verbose_name='GRADEAMENTO_2')),
                ('STATUS_DA_UNIDADE_DE_GRADEAMENTO_2', models.CharField(choices=[('Ativado', '🟩'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DA_UNIDADE_DE_GRADEAMENTO_2')),
                ('STATUS_DE_SAIDA_DE_GRADEAMENTO_2', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name=' STATUS_DE_SAIDA_DE_GRADEAMENTO_2')),
                ('STATUS_DE_APARELHO_DE_GRADEAMENTO_2', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DE_APARELHO_DE_GRADEAMENTO_2')),
                ('STATUS_DE_ENTRADA_DE_GRADEAMENTO_2', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DE_ENTRADA_DE_GRADEAMENTO_2')),
                ('STATUS_DO_RASPADOR_DE_GRADEAMENTO_2', models.CharField(choices=[('Ativado', '🟩'), ('Manutenção', '🟨'), ('Desativado', '🟥')], default='Ativado', max_length=10, verbose_name='STATUS_DO_RASPADOR_DE_GRADEAMENTO_2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAtivacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=255)),
                ('acao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='core',
        ),
    ]
